mqtt:
  hostname: 127.0.0.1
  port: 1234 #defaults to 1883
  user: test
  password: test
deviceName: test
client_id: test
external_temp_humid_sensor_pin: 4
timezone: Europe/Brussels
power_integer_state: false #defaults to false
update_interval: 60 #Defaults to 60
check_wifi_strength: true 